# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The generated root module that wires the materialized units in.

Terraform compiles a module no root module references. The validate step
runs `terraform validate` at the clone root and in each unit directory, but
the root pass — the one that sees the units and the landing-zone draft
together — never read a line of unit code, because nothing at the root
referenced `translation-units/*` (DESIGN §14 issue 14). This module
generates that reference: one `module` block per materialized unit
directory that carries Terraform, written to a single file at the clone
root and regenerated in full on every materialization.

Only directories with a `.tf` file of their own are wired. YAML-only units
(storage classes, the shared Gateway, tenancy) have no Terraform to compile
and are covered by the manifest gate instead; terraform refuses a module
directory with no configuration files, so wiring one would break the root
pass rather than widen it. A unit whose Terraform sits only in
subdirectories is compiled by NO pass at all — plan_wiring surfaces it as
`nested_tf` and the validate tool fails the run on it rather than shipping
code nothing read.

Module arguments are wired, never invented. The worker contract
(TRANSLATE_RULES) orders every unit to declare variables (var.project_id,
var.region, ...) rather than invent values, so a contract-compliant unit
carries required variables — a variable-free call would fail the root pass
on `Missing required argument` for essentially every real unit. Each wired
call therefore passes `<name> = var.<name>` for every required
(default-less) variable the unit's own top-level `.tf` files declare — and
for every DEFAULTED variable whose name the root knows (a root declaration
or a recorded fact the tfvars printer prints), because an unwired default
silently outvotes the known value at plan/apply (the 2026-08-15 e2e's
`cluster_name` case). The generated file declares any wired name the clone
root does not already declare. The pass-through declarations are valueless
by design: `terraform validate` needs no variable values, and the values
are the tfvars printer's to print (tfvars_printer.py) — a recorded fact is
emitted into `migration.auto.tfvars`, an unrecorded one is a validate
finding, and neither is ever a default here. A required variable named
like a module meta-argument (`source`, `count`, ...) cannot be passed on a
call at all; such a unit is surfaced as `unsatisfied` and the validate
tool fails the run on it rather than wiring a call that cannot compile.
"""

import os
import re

# Single generated file at the clone root, overwritten whole every run.
WIRING_FILENAME = "translation-units.tf"

HEADER_LINES = [
    "# Generated by GKE Agentic Migration (translation validate step).",
    "# Rewritten in full on every validation run — edit the units, not this file.",
    "#",
    "# Terraform compiles a module no root module references: without these",
    "# blocks, `terraform validate` at this root passes without reading a single",
    "# line of the generated unit code.",
]

# HCL identifiers allow letters, digits, underscores and dashes; the unit
# directory slug additionally allows dots, so it is not a label as it stands.
_LABEL_UNSAFE = re.compile(r"[^A-Za-z0-9_-]+")

# Meta-arguments of a `module` block: a unit variable by one of these names
# cannot be passed as an argument on the generated call, so a unit requiring
# one is unsatisfiable (plan_wiring's `unsatisfied`), never wired.
_META_ARGUMENTS = frozenset(
    {"source", "version", "count", "for_each", "providers", "depends_on",
     "lifecycle"})


def module_label(unit_id: str) -> str:
    """The Terraform module label for a unit id.

    The constant `unit-` prefix is what keeps a unit id starting with a digit
    (or sanitized down to nothing) from producing an invalid identifier.
    """
    slug = _LABEL_UNSAFE.sub("-", str(unit_id)).strip("-")
    return f"unit-{slug}" if slug else "unit"


def has_terraform(dir_path: str) -> bool:
    """True when the directory holds at least one `.tf` file of its own.

    Not recursive, deliberately: a module reads only the named directory's
    own `.tf` files, and terraform errors on a module directory with none.
    A unit whose Terraform sits only in subdirectories cannot be wired at
    all — see nested_terraform_only, which makes that a finding rather
    than a silently unreachable unit.
    """
    try:
        names = os.listdir(dir_path)
    except OSError:
        return False
    return any(n.endswith(".tf") and os.path.isfile(os.path.join(dir_path, n))
               for n in names)


def nested_terraform_only(dir_path: str) -> bool:
    """True when `.tf` files exist only BELOW the directory's top level.

    Such a unit is compiled nowhere: it cannot be wired (terraform refuses
    a module directory with no configuration files of its own) and its own
    per-directory validate pass succeeds vacuously for the same reason —
    the exact relocated form of the issue-14 silent pass. `.terraform/` is
    ignored: init droppings are not the unit's code.
    """
    if has_terraform(dir_path):
        return False
    for root, dirs, names in os.walk(dir_path):
        dirs[:] = [d for d in dirs if d != ".terraform"]
        if root != dir_path and any(n.endswith(".tf") for n in names):
            return True
    return False


def _strip_hcl(text: str) -> str:
    """Comments and heredocs blanked; braces inside strings neutralized.

    Just enough HCL lexing for variables_in: brace counting and `default =`
    detection must not trip over a `}` inside a quoted string, a heredoc,
    or a comment. String content otherwise survives (variable names live in
    strings), and newlines survive so line anchors keep working.
    """
    out, i, n = [], 0, len(text)
    while i < n:
        ch = text[i]
        if ch == '"':
            out.append('"')
            i += 1
            while i < n and text[i] != '"':
                if text[i] == "\\":
                    out.append("  ")
                    i += 2
                    continue
                out.append(" " if text[i] in "{}" else text[i])
                i += 1
            out.append('"')
            i += 1
        elif text.startswith(("#", "//"), i):
            while i < n and text[i] != "\n":
                i += 1
        elif text.startswith("/*", i):
            end = text.find("*/", i + 2)
            j = n if end < 0 else end + 2
            out.append("\n" * text.count("\n", i, j))
            i = j
        elif text.startswith("<<", i):
            m = re.match(r"<<[-~]?([A-Za-z_][A-Za-z0-9_-]*)\r?\n", text[i:])
            if not m:
                out.append(ch)
                i += 1
                continue
            tail = re.search(r"^[ \t]*" + re.escape(m.group(1)) + r"[ \t]*$",
                             text[i + m.end():], re.M)
            j = n if not tail else i + m.end() + tail.end()
            out.append("\n" * text.count("\n", i, j))
            i = j
        else:
            out.append(ch)
            i += 1
    return "".join(out)


def declared_variables(dir_path: str, exclude: frozenset = frozenset()) -> dict:
    """{name: {"has_default", "file", "line"}} for a directory's own .tf files.

    Reads only top-level files — exactly what a module call (or the root
    pass) compiles. `exclude` skips file names: the generator's own output
    must not read as a root declaration. Detection is lexical (_strip_hcl,
    then innermost-brace folding, so a `default` inside a nested `type` or
    `validation` block does not count); a worker-authored shape it misreads
    fails the root validate loudly rather than shipping silently. A name
    declared twice keeps its first file/line (the pointer serves a human)
    and OR-folds has_default, matching what the root pass would reject
    anyway. `file`/`line` point at the declaration — the tfvars printer's
    no-source finding names them, so the reviewer lands on the variable
    rather than grepping for it.
    """
    declared = {}
    try:
        names = sorted(os.listdir(dir_path))
    except OSError:
        return declared
    for file_name in names:
        full = os.path.join(dir_path, file_name)
        if (not file_name.endswith(".tf") or file_name in exclude
                or not os.path.isfile(full)):
            continue
        try:
            with open(full, "r", encoding="utf-8") as f:
                text = _strip_hcl(f.read())
        except OSError:
            continue
        for m in re.finditer(r'^[ \t]*variable[ \t]+"([^"]+)"[ \t]*\{', text, re.M):
            depth, j = 1, m.end()
            while j < len(text) and depth:
                depth += {"{": 1, "}": -1}.get(text[j], 0)
                j += 1
            body = text[m.end():j]
            while True:
                folded = re.sub(r"\{[^{}]*\}", " ", body)
                if folded == body:
                    break
                body = folded
            has_default = bool(re.search(r"^[ \t]*default[ \t]*=", body, re.M))
            name = m.group(1)
            if name in declared:
                declared[name]["has_default"] |= has_default
            else:
                declared[name] = {"has_default": has_default, "file": file_name,
                                  "line": text.count("\n", 0, m.start()) + 1}
    return declared


def variables_in(dir_path: str, exclude: frozenset = frozenset()) -> dict:
    """{name: has_default} — declared_variables without the positions."""
    return {name: info["has_default"]
            for name, info in declared_variables(dir_path, exclude).items()}


def plan_wiring(clone_dir: str, placed: dict,
                known_values: frozenset = frozenset()) -> dict:
    """Which materialized units the root module will reference.

    `placed` is the materializer's {unit_id: clone-relative dir}. Returns
    {"modules": [{"label", "unit_id", "source", "args"}], "unwired":
    [unit_id], "nested_tf": [unit_id], "unsatisfied": [{"unit_id",
    "variables"}], "declared_vars": [name]}, ordered by unit id so the
    generated file is byte-stable across runs. `unwired` units carry no
    Terraform of their own (YAML-only — the manifest gate covers them);
    `nested_tf` units carry Terraform only below their top level, which NO
    pass would compile; `unsatisfied` units require a variable named like
    a module meta-argument, which no call can pass — the caller must treat
    both of those as validation findings, never a quiet skip. `args` are
    the unit's required (default-less) variable names, each wired as
    `<name> = var.<name>`; `declared_vars` are the ones the clone root's
    own top-level files do not already declare, so the generated file
    declares them (valueless pass-throughs — validate needs no values).

    A unit variable WITH a default is also wired when the root already
    knows its name: it appears among the clone root's own declarations, or
    in `known_values` — the names the tfvars printer holds a recorded
    value for. An unwired default silently outvotes the known value at
    plan/apply, which is how the 2026-08-15 e2e's node pool targeted the
    SOURCE cluster's name: `cluster_name` defaulted to "acme-prod", the
    root never passed the real name, validate and plan were both green,
    and apply died on a cluster that does not exist. A defaulted name the
    root does NOT know stays the unit's own — those defaults are the
    unit's legitimate interior choices, not shadowed facts.

    Two unit ids can slug to one directory (the materializer's own slug is
    not injective) and two ids can sanitize to one label; both would make
    terraform refuse the file for a duplicate module call, so a directory is
    wired once and a label collision is numbered.
    """
    modules, unwired, nested, unsatisfied = [], [], [], []
    seen_dirs, seen_labels = set(), set()
    root_vars = set(variables_in(clone_dir, exclude=frozenset({WIRING_FILENAME})))
    known_names = root_vars | set(known_values)
    declared_vars = set()
    for unit_id, rel_dir in sorted(placed.items()):
        source = str(rel_dir).replace(os.sep, "/").strip("/")
        if not source or not has_terraform(os.path.join(clone_dir, rel_dir)):
            if source and nested_terraform_only(os.path.join(clone_dir, rel_dir)):
                nested.append(unit_id)
            else:
                unwired.append(unit_id)
            continue
        if source in seen_dirs:
            unwired.append(unit_id)
            continue
        seen_dirs.add(source)
        unit_vars = variables_in(os.path.join(clone_dir, rel_dir))
        required = sorted(n for n, has_default in unit_vars.items()
                          if not has_default)
        reserved = [n for n in required if n in _META_ARGUMENTS]
        if reserved:
            unsatisfied.append({"unit_id": unit_id, "variables": reserved})
            continue
        # Defaulted names the root knows are wired too (see the docstring's
        # cluster_name case); a defaulted meta-argument name just keeps its
        # default — it cannot be passed, and nothing breaks when it is not.
        overridden = (n for n, has_default in unit_vars.items()
                      if has_default and n in known_names
                      and n not in _META_ARGUMENTS)
        wired = sorted(set(required) | set(overridden))
        base = module_label(unit_id)
        label, n = base, 1
        while label in seen_labels:
            n += 1
            label = f"{base}-{n}"
        seen_labels.add(label)
        declared_vars.update(n for n in wired if n not in root_vars)
        modules.append({"label": label, "unit_id": unit_id,
                        "source": f"./{source}", "args": wired})
    return {"modules": modules, "unwired": unwired, "nested_tf": nested,
            "unsatisfied": unsatisfied, "declared_vars": sorted(declared_vars)}


def _block(module: dict) -> str:
    """One module block, byte-exact — render writes it and dropped_modules
    re-reads it, so alteration is as detectable as deletion."""
    lines = [f'module "{module["label"]}" {{',
             f'  source = "{module["source"]}"']
    lines += [f"  {name} = var.{name}" for name in module.get("args") or []]
    return "\n".join(lines) + "\n}"


def _declaration(name: str) -> str:
    """One valueless pass-through variable declaration. No default on
    purpose: a value here would be an invented project id or region, and
    `terraform validate` does not need one. The plan/apply value comes
    from `migration.auto.tfvars` when the ledger records it (the tfvars
    printer), and a name with no recorded value is a validate finding —
    never a default."""
    return (f'variable "{name}" {{\n'
            "  # Pass-through for the unit module calls below; supply the value\n"
            "  # at plan/apply. Declared here because the root does not declare it.\n"
            "}")


def render(modules: list, declared_vars: list = ()) -> str:
    """The wiring file's content ('' when there is nothing to wire).

    Pass-through declarations come before the module blocks that reference
    them. A declaration the fix loop deletes fails the root validate on an
    undeclared-variable reference, so it needs no separate byte-check; the
    module blocks get one (dropped_modules) because deleting a block makes
    terraform go quiet, not loud.
    """
    if not modules:
        return ""
    parts = ["\n".join(HEADER_LINES)]
    parts += [_declaration(name) for name in declared_vars or []]
    parts += [_block(m) for m in modules]
    return "\n\n".join(parts) + "\n"


def _is_generated(path: str) -> bool:
    """True when the file opens with this generator's banner line."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.readline().rstrip("\r\n") == HEADER_LINES[0]
    except OSError:
        return False


def write(clone_dir: str, placed: dict,
          known_values: frozenset = frozenset()) -> dict:
    """Generates the root wiring file (or removes a stale generated one).

    Returns the plan, with `file` naming what is on disk — None when no
    materialized unit carries Terraform. A previous run's GENERATED file is
    deleted in that case: left behind, it would reference directories this
    run emptied (a revised unit that dropped its Terraform), and terraform
    would fail the whole root on a missing module rather than validate what
    actually shipped.

    The clone is the customer's target repository: a file at this name that
    does not open with the generator's banner is theirs, and is never
    overwritten or removed. The plan's `foreign_file` names it instead —
    the caller must report it as a finding (the wiring was NOT written, so
    the root pass does not reach the units) and leave the question of the
    file to the reviewer.
    """
    plan = plan_wiring(clone_dir, placed, known_values)
    plan["foreign_file"] = None
    path = os.path.join(clone_dir, WIRING_FILENAME)
    if os.path.exists(path) and not _is_generated(path):
        plan["file"] = None
        plan["foreign_file"] = WIRING_FILENAME
        return plan
    content = render(plan["modules"], plan["declared_vars"])
    if content:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        plan["file"] = WIRING_FILENAME
    else:
        if os.path.exists(path):
            os.remove(path)
        plan["file"] = None
    return plan


def dropped_modules(clone_dir: str, plan: dict) -> list:
    """Wired module labels whose generated block is not intact on disk.

    The wiring file sits at the clone root, so it is part of the root
    directory's auto-fix file set: a repair worker handed a unit-level error
    it cannot reach from the root can "fix" it by deleting the module block —
    or, just as fatally for the guarantee, by repointing its `source` at a
    sibling unit or rewriting the wired arguments (the arguments are derived
    from the unit's own declared variables; a repair that edits them is
    answering an error whose code it cannot see). The generated block is
    byte-exact, so re-reading it after the validation run turns deletion AND
    alteration into findings instead of a green report.
    """
    modules = plan.get("modules") or []
    if not modules:
        return []
    path = os.path.join(clone_dir, plan.get("file") or WIRING_FILENAME)
    try:
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return [m["label"] for m in modules]
    return [m["label"] for m in modules if _block(m) not in text]
