# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The tfvars printer: the recorded values behind the root's variables.

The no-invention contract pushes values OUT of the generated code: units
declare variables instead of inventing project ids (TRANSLATE_RULES), and
the root wiring pulls each one up to the clone root as a valueless
declaration. Correct — and one link short: `terraform validate` needs no
values, so a clone validates green and still halts `terraform plan` on
`No value for required variable`, for values the migration knew all
along. In the 2026-08-15 e2e a human answered that halt by hand-authoring
35 lines of tfvars — one value of which was an invention, the exact
failure mode the contract exists to prevent.

This module prints the last link, deterministically (no LLM):

- `collect_values` reads the decision layer — the workspace settings
  every tool call already holds (`gcp_project`) and the landing-zone
  design's own literals (the clone's single `google_container_cluster`) —
  the same recorded facts the exports derivations read (DESIGN §4.6).
- `emit` writes `migration.auto.tfvars` at the clone root: one printed
  value per root variable the facts table covers, each under a comment
  naming its source. terraform auto-loads `*.auto.tfvars`, the validation
  .gitignore force-includes it with a `!` negation (the canonical
  Terraform .gitignore excludes `*.tfvars` — without the negation a
  customer ignore rule would silently drop the printed values from the
  PR while the report said they shipped), and the PR submission's
  `git add -A` ships it — the values travel with the code they
  parameterize.
- A no-default root variable the facts do NOT cover is returned in
  `missing`, pointing at the declaring file and line; the validate tool
  fails the run on it. A value the ledger does not record is never
  guessed: not a printed guess, not a variable default (a default is an
  invented value, and the worst case is a wrong value applying silently —
  the rejected alternative in the DESIGN decision record).

The customer-file discipline is the root wiring's: a file at the tfvars
name that does not open with the generator's banner belongs to the target
repository and is never overwritten or removed — `foreign_file` names it
and the caller reports the finding.
"""

import os
import re

from . import root_wiring

# Single generated file at the clone root; `*.auto.tfvars` is the name
# shape terraform loads at plan/apply with no flag.
TFVARS_FILENAME = "migration.auto.tfvars"

HEADER_LINES = [
    "# Generated by GKE Agentic Migration (translation validate step).",
    "# Every value below is a recorded migration fact — workspace settings or",
    "# a landing-zone design literal; its source is named above each line.",
    "# Rewritten in full on every validation run: to change a value, change",
    "# the recorded fact, not this file.",
]

# A GCP region ("us-central1"); zones add a letter suffix ("us-central1-a").
# A zonal cluster's location must never be printed as a region value.
_REGION_RE = re.compile(r"[a-z]+-[a-z]+\d+")

_CLUSTER_RE = re.compile(r'resource\s+"google_container_cluster"\s+"[^"]+"\s*\{')

# The clone subdirectory the units materialize into. Duplicated rather than
# imported (tools.py imports THIS module) and pinned against
# tools.UNITS_SUBDIR by tfvars_printer_test — the coverage gate's pattern.
UNITS_SUBDIR = "translation-units"


def _fold_nested(body: str) -> str:
    """The block body with every nested {...} blanked — top-level attrs only.

    declared_variables' innermost-brace folding, for the same reason: a
    `name` inside `node_pool { }` or `resource_labels = { }` is NOT the
    cluster's name, and printing it as one would ship a wrong value
    wearing a recorded-fact provenance comment.
    """
    while True:
        folded = re.sub(r"\{[^{}]*\}", " ", body)
        if folded == body:
            return body
        body = folded


def _block_body(text: str, open_brace: int) -> str:
    """The brace-matched body starting at text[open_brace] == '{'.

    Runs over _strip_hcl output, where braces inside strings, comments and
    heredocs are already blanked, so counting is exact.
    """
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace + 1:i]
    return text[open_brace + 1:]


def _literal_attr(body: str, attr: str):
    """The attribute's literal string value, or None when it is computed.

    `$` and `%` are both excluded: `${...}` interpolations AND `%{...}`
    directives make a value computed, and _strip_hcl has already blanked
    the braces, so without the exclusion a directive-bearing string would
    read as a (mangled) literal.
    """
    m = re.search(r'^[ \t]*' + re.escape(attr) + r'[ \t]*=[ \t]*"([^"$%]*)"[ \t]*$',
                  body, re.M)
    return m.group(1) if m else None


def scan_clusters(clone_dir: str) -> list:
    """[{name, location, project}] for the landing zone's clusters.

    The same fact the deployment scan (`actions.scan_container_clusters`)
    feeds the exports cluster derivation — literal attributes only, a
    computed value read as None — re-read here rather than imported: the
    deployment module carries live-cloud dependencies this offline step
    must not load. Two disciplines on top of it. Comments, heredocs and
    strings' braces are blanked first (root_wiring._strip_hcl) and nested
    blocks folded away (_fold_nested), so neither a commented-out cluster
    nor a `node_pool { name = ... }` reads as the cluster's own fact. And
    the translation-units/ subtree is skipped, matching the coverage
    gate's ownership: a unit-declared cluster is that gate's
    owner-boundary finding, never a reason for the printer to silently
    drop the landing zone's own facts.
    """
    clusters = []
    for dirpath, dirnames, filenames in os.walk(clone_dir):
        skip = {".git", ".terraform"}
        if dirpath == clone_dir:
            skip.add(UNITS_SUBDIR)
        dirnames[:] = sorted(d for d in dirnames if d not in skip)
        for name in sorted(filenames):
            if not name.endswith(".tf"):
                continue
            try:
                with open(os.path.join(dirpath, name), "r", encoding="utf-8") as f:
                    text = root_wiring._strip_hcl(f.read())
            except OSError:
                continue
            for match in _CLUSTER_RE.finditer(text):
                body = _fold_nested(_block_body(text, match.end() - 1))
                clusters.append({"name": _literal_attr(body, "name"),
                                 "location": _literal_attr(body, "location"),
                                 "project": _literal_attr(body, "project")})
    return clusters


def collect_values(config: dict, clone_dir: str) -> dict:
    """{variable name: {"value", "source"}} — every fact the ledger records.

    The vocabulary is deliberately small and name-keyed: the worker
    contract (TRANSLATE_RULES) and the landing-zone knowledge fix the
    canonical names (`var.project_id`-style), so the name IS the semantic
    match. A name outside this table has no recorded source; printing for
    it would be a guess, so the caller reports it instead (`emit`'s
    `missing`). Cluster facts are read only when the landing zone holds
    exactly one literal cluster — the landing-zone MUST is exactly one
    under any profile, and with two on disk "the cluster's name" is not a
    fact (the coverage gate rejects that clone on its own). The project
    follows the exports derivation's precedence: the design's own literal
    `project` attribute first, the workspace settings' `gcp_project` as
    the fallback (the recorded-fact carve-out — this is the ledger's own
    record of the target fleet host, not an invention).
    """
    values = {}
    clusters = scan_clusters(clone_dir)
    single = clusters[0] if len(clusters) == 1 else None
    if single and single["project"]:
        source = "landing-zone design literal (google_container_cluster.project)"
        values["project"] = {"value": single["project"], "source": source}
        values["project_id"] = {"value": single["project"], "source": source}
    elif (config or {}).get("gcp_project"):
        project = config["gcp_project"]
        source = "workspace settings (gcp_project)"
        values["project"] = {"value": project, "source": source}
        values["project_id"] = {"value": project, "source": source}
    if len(clusters) == 1:
        name = clusters[0]["name"]
        location = clusters[0]["location"]
        if name:
            values["cluster_name"] = {
                "value": name,
                "source": ("landing-zone design literal "
                           "(google_container_cluster.name)")}
        if location and _REGION_RE.fullmatch(location):
            values["region"] = {
                "value": location,
                "source": ("landing-zone design literal "
                           "(google_container_cluster.location)")}
    return values


def _hcl_string(value: str) -> str:
    """The value as an HCL string literal — escaped, never interpolated.

    `${` and `%{` open template sequences inside HCL strings; a recorded
    fact containing either must land as those literal characters, not as
    an expression terraform evaluates.
    """
    escaped = (str(value).replace("\\", "\\\\").replace('"', '\\"')
               .replace("${", "$${").replace("%{", "%%{"))
    return f'"{escaped}"'


def render(printed: dict) -> str:
    """The tfvars file content ('' when nothing is printed).

    `printed` is {name: {"value", "source"}}; names are sorted so the file
    is byte-stable across runs. Every assignment sits under a comment
    naming its source — the file is read in the customer's PR, where an
    unexplained literal is indistinguishable from an invented one.
    """
    if not printed:
        return ""
    parts = ["\n".join(HEADER_LINES)]
    for name in sorted(printed):
        entry = printed[name]
        parts.append(f"# source: {entry['source']}\n"
                     f"{name} = {_hcl_string(entry['value'])}")
    return "\n\n".join(parts) + "\n"


def _is_generated(path: str) -> bool:
    """True when the file opens with this generator's banner line."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.readline().rstrip("\r\n") == HEADER_LINES[0]
    except OSError:
        return False


def emit(clone_dir: str, values: dict) -> dict:
    """Writes migration.auto.tfvars (or removes a stale generated one).

    Runs AFTER root_wiring.write (the generated pass-through declarations
    count as root declarations) and AFTER the auto-fix pass (the root's
    fix worker writes root-level .tf files, so the variable set is only
    settled once the fix loop is done). Prints a value for EVERY
    root-level variable `values` records — a defaulted one included: a
    tfvars assignment legally overrides a declaration default, and an
    LLM-authored placeholder default must never outvote the ledger (the
    F-C shape, one level up). `missing` reports only the no-default
    remainder, with the declaring file and line — the caller fails the
    run on each: unprinted, such a variable is a `terraform plan` value
    prompt, which the 2026-08-15 run showed becomes a hand-authored,
    partly invented tfvars. A defaulted variable without a recorded fact
    is not missing: that default is the design's own interior choice.

    Returns {"file", "foreign_file", "printed": {name: source},
    "missing": [{"name", "file", "line"}], "content"}. `content` is what
    was written, for the caller's post-run byte re-check (`altered`). A
    file at the tfvars name without the generator's banner is the
    customer's: named as `foreign_file`, never overwritten — and `missing`
    still reports, because an unread customer file proves nothing about
    the values plan will prompt for.
    """
    declared = root_wiring.declared_variables(clone_dir)
    printed = {n: values[n] for n in sorted(declared) if n in values}
    missing = [{"name": n, "file": declared[n]["file"],
                "line": declared[n]["line"]}
               for n in sorted(declared)
               if not declared[n]["has_default"] and n not in values]
    result = {"file": None, "foreign_file": None,
              "printed": {n: v["source"] for n, v in sorted(printed.items())},
              "missing": missing, "content": None}
    path = os.path.join(clone_dir, TFVARS_FILENAME)
    if os.path.exists(path) and not _is_generated(path):
        result["foreign_file"] = TFVARS_FILENAME
        return result
    content = render(printed)
    if content:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        result["file"] = TFVARS_FILENAME
        result["content"] = content
    elif os.path.exists(path):
        os.remove(path)
    return result
